### ISSUE TITLE
the more I try the more I think I am 1head

### ISSUE THREAD

**Issue by Kayomuri** [nelpats/ValorantTS#5]
It looks really great but I'm a novice and I don't understand everything. I can't find user.json I only find user.cs and I have to change the resolution of the last 3 lines? and then how do I run the program? Maybe a little video to show the manipulation? anyway, thanks a lot but I feel like i'm really stupid haha (i don't speak english very well sorry for that)

**Comment by nelpats** [comment]
On the right side of the the screen you can see the section "Release" and you click the link "precompiled binaries" then you download the compressed archive, extract it and then you have the program

**Comment by Kayomuri** [comment]
worked, thank you very much!
