### ISSUE TITLE
not an issue, but a note/comment

### ISSUE THREAD

**Issue by ginc55** [nelpats/ValorantTS#6]
I like the programme altough is there anyway to achieve true stretch whilst playing fullscreen? Regular windowed games always show noticeable input lag, i also tried this with optimizations for windowed games on win11 which didnt change a single thing. So im hoping if  
you have an idea of how to fool the game to true stretched whilst also playing fullscreen?

**Comment by nelpats** [comment]
I don't think there's anyway to achieve true stretch on fullscreen, however i haven't noticed any input lag while using windowed. Maybe you can try to enable nvidia refelx in your game settings.
