### ISSUE TITLE
Error invalid user id

### ISSUE THREAD

**Issue by NotSoHeroic** [nelpats/ValorantTS#7]
Hey I was trying to set this up and unfortunately it says my user id is invalid, but I followed the instructions exactly, and my user id is typed in correctly in the quotations. I see there are 3 versions of the user id folder and I used the "-na" one like the setup says, but no good. I tried the others as well but no luck there either. I wasn't sure what else could be the problem do you have any suggestions for me?

**Comment by nelpats** [comment]
Hey, make sure that inside each folder named with your suerid you have another folder called Windows and that inside that folder you have a file named GameUserSettings.ini, if that's the case then it should work correctly. Also make sure that you provide the config file the full userid.

**Comment by NotSoHeroic** [comment]
Yup, so the Windows folder does have GameUserSettings.ini file in every userid folder. There are 3 separate userid folders one is the userid just by itself, the second is the userid but with "-ap" added to the end. and the last was the one mentioned in the setup it has userid plus "-na" added to the end. None of them work when put into the config file. I've followed everything precisely as stated, and still get the error. Could it have anything to do with region? I see you're github account is from France, I reside in North America. My userid doesn't start like the example provided "x9cfyg4c" buy mine starts with "4b926b80" seems to be the only thing I could think of that looks any different.

**Comment by nelpats** [comment]
It shouldn't matter, try to run the program as an Administrator, if it doesn't work, check that the id you entered in the config file is correct.

**Comment by NotSoHeroic** [comment]
Yeah I've tried running as admin, no luck. id is correct I've been copy pasting it, but I've tried typing it character by character. I'm not sure what the issue is I'm guessing there's just something wrong with my system but I'm not sure what would prevent something as simple as this. Thanks for trying anyway.

**Comment by nelpats** [comment]
I have an idea, go to "C:\Users\USER\AppData\Local\VALORANT\Saved\Config\USERID\Windows\GameUserSettings.ini" (replace USER with your windows username and USERID with your valorant userid) and check if the file is in read-only mode, if it is, uncheck, apply and try again.

**Comment by NotSoHeroic** [comment]
The file is not set to read only.

also not that it's entirely related, I did delete the VALORANT folder and did a fresh reinstall of the game, and still get the error.

**Comment by nelpats** [comment]
I will update the program soon, so that you'll have details about the error so i can have a better understanding of what's happening, also i wanted to ask you, how did you find out about this program ?

**Comment by NotSoHeroic** [comment]
I actually just stumbled upon it after learning that the in-game resolution wasn't true stretched after I had been using it for a while, I play CS and use another program called [CS:GO Streched Launcher](https://www.reddit.com/r/GlobalOffensive/comments/2o51wv/multiple_monitors_and_43_stretched_resolution/) that someone else made and essentially does the same thing as your program. I was trying to fine tune my sensitivity for Val and realized that the resolution I was using wasn't true streched, so I googled "valorant true stretched" and your program is on the first page, and the only Github link so I checked it out and here we are. Plenty of tutorials on how to do it manually but I'd rather not go into my Nvidia control panel and boot up [winexp](https://www.nirsoft.net/utils/winexp.html) to disable WS_BORDER every time I play the game.

**Comment by nelpats** [comment]
I updated the program so you can have a more detailed error about the userid.

**Comment by NotSoHeroic** [comment]
Okay so now I get.
Could not parse file (GameUserSettings.ini File path) while parsing line number 0 with value '' - IniParser version: 2.5.2.0

**Comment by nelpats** [comment]
Well, you can try to delete GameUserSettings.ini (make a backup of it just in case) and restart your game to generate another one, and then try again.
