### ISSUE TITLE
Black bars

### ISSUE THREAD

**Issue by ghost** [nelpats/ValorantTS#9]
Regardless of what i do, i followed your steps 1:1 and i still get black bars. Not sure why that is..

**Comment by ghost** [comment]
Once your program stretches it, the game seems to revert back to letterbox. No clue why

![image](https://github.com/nelpats/ValorantTS/assets/45088542/e0c3a7c0-a8c9-4c67-bc6c-26929feb6f26)

**Comment by nelpats** [comment]
I don't have this issue, but you can try to check your Nvidia control panel settings to make sure you're using stretched res.
